/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 62d83a792da89848b134898bb04f3aa5)
interface __BaseEnv_Env {
	STATIC_FILES: R2Bucket;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
