/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: da523c64da82929954e70b633838db12)
interface __BaseEnv_Env {
	STATIC_FILES: R2Bucket;
	SHORTLINK_ANALYTICS: AnalyticsEngineDataset;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
